In [1]:
import pandas as pd
import numpy as np
import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras import layers
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

Using TensorFlow backend.
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Alessandro\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
df1 = pd.read_excel(r"D:\Personale\Uniroma3\Da fare\ML\Progetto\Dataset_aggiornato.xlsx")

In [3]:
df1

,Player_ID,Surname,First_name,Player,Club,Season_ID,Starting_11,Goals,Assists,Owngoals,Substitutions_on,Substitutions_off,Yellow_cards,Red_yellow_cards,Red_cards,Penalty_goals,POSITION,Date_of_birth,Year_of_birth,Age
0,10,Klose,Miroslav,Miroslav Klose,SS Lazio,2015,14,7,8,0,10,9,3,0,0,1,Centre-Forward,1978-06-09,1978,37
1,2865,Lichtsteiner,Stephan,Stephan Lichtsteiner,Juventus FC,2015,22,0,1,0,4,11,5,0,0,0,Right-Back,1984-01-16,1984,31
2,3417,Burdisso,Nicolás,Nicolás Burdisso,Genoa CFC,2015,28,0,0,0,0,1,7,0,0,0,Centre-Back,1981-04-12,1981,34
3,3507,Abbiati,Christian,Christian Abbiati,AC Milan,2015,0,0,0,0,1,0,0,0,0,0,Goalkeeper,1977-07-08,1977,38
4,3713,Maccarone,Massimo,Massimo Maccarone,FC Empoli,2015,35,13,4,0,2,20,4,0,0,1,Centre-Forward,1979-09-06,1979,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3517,481344,Russo,Alessandro,Alessandro Russo,US Sassuolo,2019,0,0,0,0,0,0,0,0,0,0,Goalkeeper,2001-03-31,2001,18
3518,273236,Santos da Silva Barbosa,Marlon,Marlon,US Sassuolo,2019,182,0,0,0,13,26,52,0,0,0,Centre-Back,1995-09-07,1995,24
3519,129674,Toljan,Jeremy,Jeremy Toljan,US Sassuolo,2019,273,13,26,0,26,39,91,0,0,0,Right-Back,1994-08-08,1994,25
3520,391065,Traorè,Hamed Junior,Hamed Junior Traorè,US Sassuolo,2019,169,39,13,0,91,104,26,0,0,0,Attacking Midfield,2000-02-16,2000,19
3521,357176,Tripaldelli,Alessandro,Alessandro Tripaldelli,US Sassuolo,2019,13,0,0,0,13,0,0,0,0,0,Left-Back,1999-02-09,1999,20

In [4]:
df1.Surname[740] #controllo che l'ultimo giocatore della stagione 2015 sia "verde"

'Verde'

In [5]:
df1_2015 = df1[0:740] #dati generali del 2015

In [6]:
df1_2015.head()

,Player_ID,Surname,First_name,Player,Club,Season_ID,Starting_11,Goals,Assists,Owngoals,Substitutions_on,Substitutions_off,Yellow_cards,Red_yellow_cards,Red_cards,Penalty_goals,POSITION,Date_of_birth,Year_of_birth,Age
0,10,Klose,Miroslav,Miroslav Klose,SS Lazio,2015,14,7,8,0,10,9,3,0,0,1,Centre-Forward,1978-06-09,1978,37
1,2865,Lichtsteiner,Stephan,Stephan Lichtsteiner,Juventus FC,2015,22,0,1,0,4,11,5,0,0,0,Right-Back,1984-01-16,1984,31
2,3417,Burdisso,Nicolás,Nicolás Burdisso,Genoa CFC,2015,28,0,0,0,0,1,7,0,0,0,Centre-Back,1981-04-12,1981,34
3,3507,Abbiati,Christian,Christian Abbiati,AC Milan,2015,0,0,0,0,1,0,0,0,0,0,Goalkeeper,1977-07-08,1977,38
4,3713,Maccarone,Massimo,Massimo Maccarone,FC Empoli,2015,35,13,4,0,2,20,4,0,0,1,Centre-Forward,1979-09-06,1979,36

In [7]:
df2 = pd.read_excel(r"D:\Personale\Uniroma3\Da fare\ML\Progetto\Dataset_aggiornato.xlsx", sheet_name=1)

In [8]:
df2

,player_injury_ID,Season_ID,Player_ID,Surname,First_name,Player,Injury_ID,Injury_English,Injury_Italian,Inrured_from,Injured_until,Injury_days
0,44899,2015,68864,Strootman,Kevin,Kevin Strootman,165,Knee-OP,Operazione al ginocchio,2015-01-29,2015-10-19 00:00:00,263.0
1,52671,2015,73083,Zuculini,Franco,Franco Zuculini,109,Cruciate Ligament Surgery,Operazione al legamento crociato,2015-04-02,2015-12-12 00:00:00,254.0
2,53511,2015,130382,Mbakogu,Jerry,Jerry Mbakogu,101,Unknown Injury,Infortunio,2015-05-09,2015-09-12 00:00:00,126.0
3,52289,2015,110923,Perin,Mattia,Mattia Perin,65,NaN,Infortunio alla spalla,2015-06-08,2015-10-15 00:00:00,129.0
4,50607,2015,29835,Blaszczykowski,Jakub,Jakub Blaszczykowski,58,muscular problems,Problema muscolare,2015-07-06,2015-07-09 00:00:00,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3649,138202,2019,283735,Zaccagni,Mattia,Mattia Zaccagni,374,coronavirus,Coronavirus,2020-03-17,2020-04-01 00:00:00,15.0
3650,138195,2019,33923,Matuidi,Blaise,Blaise Matuidi,374,coronavirus,Coronavirus,2020-03-17,2020-04-15 00:00:00,29.0
3651,138315,2019,206050,Dybala,Paulo,Paulo Dybala,374,coronavirus,Coronavirus,2020-03-20,0000-00-00,NaN
3652,138357,2019,199976,Sportiello,Marco,Marco Sportiello,374,coronavirus,Coronavirus,2020-03-24,2020-04-07 00:00:00,14.0
3653,138477,2019,41414,Leiva,Lucas,Lucas Leiva,165,Knee-OP,Operazione al ginocchio,2020-04-04,2020-05-04 00:00:00,30.0

In [9]:
df2.Surname[733] #check sull'ultimo giocatore del 2015

'Citadin Martins'

In [10]:
df2_2015 = df2[0:733] #dati injured stagione 2015

In [11]:
ID1 = df1_2015["Player_ID"] #ID giocatori stagione 2015

In [12]:
ID2 = df2_2015["Player_ID"] #ID giocatori stagione 2015

In [13]:
ID1 = pd.DataFrame(ID1) #creo un dataframe

In [14]:
ID2 = pd.DataFrame(ID2) #creo un dataframe

In [15]:
index = np.in1d(ID1, ID2)

In [16]:
index2 = np.where(index == True)

In [17]:
df1_2015["class"] = index

C:\Users\Alessandro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [18]:
df1_2015["class"].loc[df1_2015["class"] == True] = 1

C:\Users\Alessandro\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Alessandro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [19]:
df1_2015["class"].loc[df1_2015["class"] == False] = 0

C:\Users\Alessandro\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [20]:
df1_2015.drop(["Player_ID", "Surname", "First_name", "Player", "Season_ID", "Date_of_birth", "Year_of_birth"], axis = 'columns', inplace = True)

C:\Users\Alessandro\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [21]:
df1_2015

,Club,Starting_11,Goals,Assists,Owngoals,Substitutions_on,Substitutions_off,Yellow_cards,Red_yellow_cards,Red_cards,Penalty_goals,POSITION,Age,class
0,SS Lazio,14,7,8,0,10,9,3,0,0,1,Centre-Forward,37,1
1,Juventus FC,22,0,1,0,4,11,5,0,0,0,Right-Back,31,1
2,Genoa CFC,28,0,0,0,0,1,7,0,0,0,Centre-Back,34,1
3,AC Milan,0,0,0,0,1,0,0,0,0,0,Goalkeeper,38,0
4,FC Empoli,35,13,4,0,2,20,4,0,0,1,Centre-Forward,36,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,Frosinone Calcio,25,1,0,0,1,1,8,0,0,0,Centre-Back,28,1
736,Frosinone Calcio,0,0,0,0,0,0,0,0,0,0,Goalkeeper,26,0
737,Frosinone Calcio,4,0,0,0,1,2,1,0,0,0,Centre-Back,24,0
738,Frosinone Calcio,0,0,0,0,0,0,0,0,0,0,Right-Back,32,0
739,Frosinone Calcio,3,0,0,0,3,1,1,0,0,0,Centre-Forward,22,0

In [22]:
from sklearn.compose import make_column_transformer

In [23]:
# applico
column_trans = make_column_transformer((OneHotEncoder(), ["Club","POSITION"]), remainder="passthrough")

In [24]:
array = column_trans.fit_transform(df1_2015)

In [25]:
array.shape

(740, 45)

In [26]:
#distinguo due dataset, uno con le feature e uno con la classe ossia il fattore di classificazione, tutto tramite subsetting
df, cl = (array[:,0:47], df1_2015["class"])

In [27]:
cl.shape

(740,)

In [28]:
df.shape

(740, 45)

In [29]:
df

array([[0.0, 0.0, 0.0, ..., 1, 37, 1],
       [0.0, 0.0, 0.0, ..., 0, 31, 1],
       [0.0, 0.0, 0.0, ..., 0, 34, 1],
       ...,
       [0.0, 0.0, 0.0, ..., 0, 24, 0],
       [0.0, 0.0, 0.0, ..., 0, 32, 0],
       [0.0, 0.0, 0.0, ..., 0, 22, 0]], dtype=object)

In [30]:
#creo i dataset
x_train, x_test, y_train, y_test = train_test_split(df, cl, test_size=0.3, random_state = 12345)

In [31]:
#ulteriore passo di preprocessing
y_train = np_utils.to_categorical(y_train,2)
y_test = np_utils.to_categorical(y_test,2)

In [32]:
#creo il modello neurale

In [33]:
model = Sequential() #inizializzo il modello

In [34]:
#aggiungo i layers e i neuroni
model.add(layers.Dense(45, input_dim = x_train.shape[1], activation="relu"))
#procedo aggiungendo un altro strato
model.add(layers.Dense(22, activation="relu")) #la funzione di attivazione è la rectified linear unit
model.add(layers.Dense(11, activation="relu"))
model.add(layers.Dense(5, activation="relu"))
#strato id uscita
model.add(layers.Dense(2, activation="softmax")) #2 neuroni siccome le possibili classifcazioni sono 2, la funzione softmax meglio si adatta ai probl. di classificazior multipla

In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 45)                2070
_________________________________________________________________
dense_2 (Dense)              (None, 22)                1012
_________________________________________________________________
dense_3 (Dense)              (None, 11)                253
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 60
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 12
=================================================================
Total params: 3,407
Trainable params: 3,407
Non-trainable params: 0
_________________________________________________________________

In [36]:
#compilo il modello con funzione di perdita, ottimizzatore e metrica
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [37]:
#applico sugli oggetti di test
score = model.evaluate(x_test, y_test)

WARNING:tensorflow:From C:\Users\Alessandro\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

222/222 [==============================] - 0s 144us/step

In [38]:
score[1]

0.6171171069145203